version: 0.4
outputdir: ./bin
scripts:
  fmt: goimports -w src
projects:
  - name: catalog
    type: go
    root: src/bin/catalog
    imageName: gcr.io/otsimocloud/catalog
    dockerfile: Dockerfile
    run: ./catalog --debug --storage mongodb
    golang:
      package: bin/catalog
      cgoEnabled: false
      ldflags: "-w -X main.Version=${BUILD_VERSION}"
      builder: gb
    develop:
      ports:
        - "30857:18857"