[catalog]
title = "sample"
visible_at = "2016-01-20T23:30"
valid_days = 14

[[featured]]
game_name = "game-1"
[[featured]]
game_name = "game-2"
[[featured]]
game_name = "game-3"

[[new]]
game_name = "game-1"
[[new]]
game_name = "game-2"
[[new]]
game_name = "game-3"

[[popular]]
game_name = "game-1"
[[popular]]
game_name = "game-2"
[[popular]]
game_name = "game-3"
